/**
 * Fetches real elevation profiles for all 50 mountains using OpenTopoData (SRTM 30m).
 * Samples 61 points along a W→E transect ±6 km through each peak.
 * Run with: npx tsx scripts/fetch-profiles.ts
 */

import { writeFileSync } from 'fs';
import { mountains } from '../src/data/mountains';

const POINTS = 61;
const SPAN_LNG = 0.09;   // ±0.09° ≈ ±6 km at Ireland's latitude
const DELAY_MS = 1200;   // OpenTopoData free tier: 1 req/sec

function buildLocations(lat: number, lng: number): string {
  const pts: string[] = [];
  for (let i = 0; i < POINTS; i++) {
    const t = i / (POINTS - 1);
    const sampleLng = (lng - SPAN_LNG) + t * SPAN_LNG * 2;
    pts.push(`${lat.toFixed(6)},${sampleLng.toFixed(6)}`);
  }
  return pts.join('|');
}

async function fetchProfile(lat: number, lng: number): Promise<number[]> {
  const url = `https://api.opentopodata.org/v1/srtm30m?locations=${buildLocations(lat, lng)}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  const json = await res.json() as { results: Array<{ elevation: number }> };
  return json.results.map(r => Math.max(0, Math.round(r.elevation)));
}

async function main() {
  console.log(`Fetching elevation profiles for ${mountains.length} mountains…\n`);
  const profiles: Record<number, number[]> = {};

  for (const m of mountains) {
    process.stdout.write(`  [${String(m.id).padStart(2)}] ${m.name.padEnd(30)} `);
    try {
      profiles[m.id] = await fetchProfile(m.lat, m.lng);
      const peak = Math.max(...profiles[m.id]);
      console.log(`✓  (peak in profile: ${peak}m)`);
    } catch (e) {
      console.log(`✗  ${e}`);
      profiles[m.id] = [];
    }
    await new Promise(r => setTimeout(r, DELAY_MS));
  }

  const lines = mountains
    .map(m => `  ${m.id}: [${(profiles[m.id] ?? []).join(',')}]`)
    .join(',\n');

  const output = `// Auto-generated by scripts/fetch-profiles.ts — do not edit manually.
// 61-point W→E elevation transect (SRTM 30m) centred on each mountain peak.
export const profiles: Record<number, number[]> = {
${lines},
};
`;

  writeFileSync('./src/data/profiles.ts', output, 'utf8');
  console.log('\n✅  Saved to src/data/profiles.ts');
}

main().catch(err => { console.error(err); process.exit(1); });
